options:
  logging: CLOUD_LOGGING_ONLY

steps:
# [clone policy library]
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - https://github.com/lykaasegura/w-secteam-repo.git

# [START tf-init]
- id: "tf init"
  name: gcr.io/config-validator/terraform-validator
  entrypoint: terraform
  args:
  - init
  dir: deploy/orgrole
# [END tf-init]

# [START tf-plan]
- id: 'tf plan'
  name: gcr.io/config-validator/terraform-validator
  entrypoint: terraform
  args:
  - plan
  - -out=terraform.plan
  dir: deploy/orgrole
# [END tf-plan]

# [START tf-parse for terraform validator]
- id: 'tf parse'
  name: gcr.io/config-validator/terraform-validator
  entrypoint: "/bin/bash"
  args: ["-c", "terraform show -json terraform.plan > terraform.json"]
  dir: deploy/orgrole
# [END tf-parse]

# [debug]
- id: 'debug'
  name: gcr.io/config-validator/terraform-validator
  entrypoint: "/bin/bash"
  args:
  - cat
  - ./terraform.json
  dir: deploy/orgrole

# [START tf-vet]
- id: 'tf validate'
  name: 'gcr.io/config-validator/terraform-validator'
  dir: deploy/orgrole
  entrypoint: 'terraform'
  args:
  - validate
  - terraform.json
  - --policy-path=./w-secteam-repo
# [END tf-vet]  
# start fail test r2